### ISSUE TITLE
Linux binaries require GCC-6 installed

### ISSUE THREAD

**Issue by ewrogers** [KredsBlockchain/kreds-core#1]
Attempting to run the v1.0 release binaries on Ubuntu 16.04 Xenial gives me a `libstdc++.so.6` error:
```

kredsd: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version 'CXXABI_1.3.11' not found (required by kredsd)
kredsd: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version 'GLIBCXX_3.4.22' not found (required by kredsd)
```

Unfortunately `apt-get upgrade` and `apt-get dist-upgrade` do not fix the issue.

The workaround is to install GCC-6 manually:
```
sudo add-apt-repository ppa:ubuntu-toolchain-r/test
sudo apt-get update -y
sudo apt-get install gcc-6 g++-6 -y --no-install-recommends

```
However, this seems like a strange requirement for compatibility. Is it possible to target a lower version of the C++ lib?

**Comment by BlockARTLab** [comment]
It's recommend anyone on Linux build from source cheers!
