### ISSUE TITLE
make install error

### ISSUE THREAD

**Issue by zoldur** [KredsBlockchain/kreds-core#2]
root@localhost:~/kreds-core-1.0.0.1# make install
Making install in src
make[1]: Entering directory '/root/kreds-core-1.0.0.1/src'
make[2]: Entering directory '/root/kreds-core-1.0.0.1/src'
../share/genbuild.sh: 19: [: =: unexpected operator
make[3]: Entering directory '/root/kreds-core-1.0.0.1/src'
../share/genbuild.sh: 19: [: =: unexpected operator

**Comment by BlockARTLab** [comment]
Cheers for reporting the error. Should be fixed now!
